### PR TITLE
Su kf analysis

### PR DESCRIPTION
**Pull request by KFedak**
adding analysis to the overall startup study branch

### CODE REVIEW

**Comment by nickgood** [comment]
Can you add the new data files to my drive so I can run the new .Rmd?
---

Nicholas Good, BSc. PhD.
Environmental and Radiological Health Sciences
Colorado State University
Fort Collins
Colorado
80523-1681

Tel: +1.970.491.7607
Alt: +1.970.310.3750
Email: n.good@colostate.edu<mailto:n.good@colostate.edu>

On Oct 17, 2017, at 17:40, Kristen Fedak <notifications@github.com<mailto:notifications@github.com>> wrote:


@KFedak<https://github.com/kfedak> requested your review on: nickgood/stoves_nih_2016_git#186<https://github.com/nickgood/stoves_nih_2016_git/pull/186> Su kf analysis.

**Comment by KFedak** [comment]
oh right... I just uploaded the "supporting data" folder to your drive so the new .rmd should run. However, I think I actually don't want to merge that file into the master - just the changes to the emissions_analysis_perstartup.Rmd. After further discussion with John and Jennifer, I stopped going the route I was going with that global use estimate, so that rmd is not complete or necessary to be in the startup master. Is accepting just the perstartup.rmd changes something we can do from this merge request or do I need to cancel this one and set it up differently?

**Comment by ngood13** [comment]
Should be fine as is :)



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by KFedak** [comment]
:smile: :+1:

**Comment by nickgood** [comment]
add in kristen's updates

**Pull request merged**
