### PR TITLE
Kristentest

### PR DESCRIPTION
**Pull request by KFedak**
edited the r functions script to fix bug in Kelsey's summarize function
edited the emissions factor summary rmd to work with the .rds emissions file, which is more up to date than the .rda

### CODE REVIEW

**Comment by kbilsback** [comment]
Ahhh, did you pull my overall_manuscript branch into kristentest? I need to fix that function file before it gets merged to the master. Also, it looks like some old functions I wrote are getting overwritten? Need to look into this more... Also need to do another fix to emissions summary function.

**Comment by KFedak** [comment]
hmm, I didn't think that's what happened - I had these from these two files branched from the master, and then fixed little things that were acting buggy when I tried to run them, so was merging back. but feel free to reject this merge then if seems "off"!

**Comment by kbilsback** [comment]
Oh, did you just copy and paste what I had in my branch into the master code? I think it would be better if I merged my new version from my overview_manuscript branch after I fix the bugs...but thanks for finding those issues!

**Comment by kbilsback** [comment]
The function was kind of in it's beta form when you copied it. I was meant to add another function input so that we could plot missing tests by instrument or pollutant.

**Comment by KFedak** [comment]
OOOOOH I bet that was it. Sorry! Ok yes merging request canceled :)

**Pull request closed without merging**
