### PR TITLE
Note updates

### PR DESCRIPTION
**Pull request by kbilsback**
updated notes to make them more accurate

### CODE REVIEW

**Review by ngood13 — COMMENTED** [review]
looks good

**Review by ngood13 — COMMENTED** [review]
see if you can merge now I've reviewed?

**Comment by ngood13** [comment]
looks good

**Comment by kbilsback** [comment]
I can't merge it myself 👎

**Comment by ngood13** [comment]
Can you approve my review? I can force the merge through, but it seems I there should be a way to approve  it and then merge un-forcefully.

**Review by ngood13 — APPROVED** [review]
Try merging now!

**Comment by kbilsback** [comment]
👍

**Pull request merged**
