### PR TITLE
Isee analysis

### PR DESCRIPTION
**Pull request by kbilsback**

### CODE REVIEW

**Comment by KFedak** [comment]
These commit notes are making me giggle so much 😄😊😜😘



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by kbilsback** [comment]
Color scheme is of paramount importance!! 😸

I think this should be a priority as we revisit the analysis!! 😻

**Comment by KFedak** [comment]
Haha yes! Super important! I also like the "did this in wrong branch" comment... So honest :)


Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by nickgood** [comment]
Kristen and Kelsey are the best. I love them so much. They are the most clever people I know! I will give them a raise, 10x what they are paid now! :octocat: :+1: :woman_technologist:

**Pull request closed without merging**
